### ISSUE TITLE
Docker build error 

### ISSUE THREAD

**Issue by kaceo** [pinry/docker-pinry#9]
Broken during docker build

Step 4/22 : RUN apt-get --yes build-dep python-imaging
 ---> Running in 8b16b78a0604
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to find a source package for pillow
Picking 'pillow' as source package instead of 'python-imaging'
The command '/bin/sh -c apt-get --yes build-dep python-imaging' returned a non-zero code: 100

**Comment by kaceo** [comment]
I tried to use a prebuilt image (robinthrift/docker-pinry) on docker hub, still fails:

sudo docker run -d=true -p=10000:80 -v=/mnt/pinry:/data robinthrift/docker-pinry /start

open browser to localhost:10000

returns "Internal Server Error"

**Comment by andreasabilio** [comment]
+1

**Comment by andreasabilio** [comment]
+1

**Comment by Kaput1982** [comment]
Jumping in to say I'm getting the same error as the OP.
I'm installing pinry on Ubuntu 16.04 64bit server VM, if that makes any difference.  I set docker up following the instructions from digital ocean (https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04)

Step 4/22 : RUN apt-get --yes build-dep python-imaging
 ---> Running in 2189e39af0ae
Reading package lists...
Building dependency tree...
Reading state information...
Picking 'pillow' as source package instead of 'python-imaging'
E: Unable to find a source package for pillow
The command '/bin/sh -c apt-get --yes build-dep python-imaging' returned a non-zero code: 100

**Comment by Wurzelmann** [comment]
I've got exactly the same problem as @Kaput1982 

+1

**Comment by nettiopsu** [comment]
+1

**Comment by voteleobrown** [comment]
Is it trying to install a package named "pillow" when the package should be "python-pil"?

**Comment by WinndyBoy** [comment]
anyone find a solution to this yet :)

**Comment by dwanderton** [comment]
+1

**Comment by tsmsogn** [comment]
Try apt-get --yes install python-imaging
